locale = "zh-CN"

execute_prefixes = [
  "你执行",
  "请执行",
  "帮我执行",
  "执行命令",
  "执行",
]

result_suffixes = [
  "告诉我结果",
  "并告诉我结果",
  "然后告诉我结果",
  "并把结果告诉我",
  "然后回复我",
  "并回复我",
  "告诉我输出",
]

negative_markers = [
  "是什么命令",
  "什么意思",
  "怎么用",
  "如何使用",
]
